on:
 - push
 - workflow_dispatch

env:
  CACHE_DIR: /home/runner/work/_temp/trivy

jobs:
   container_scanning_using_trivy:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v2.4.2
     - name: Build container image
       shell: pwsh
       run: ./build.ps1
     - name: Install trivy
       shell: bash
       run: |
        sudo apt-get install wget apt-transport-https gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
     - name: Trivy Database Download
       run: trivy image alpine --download-db-only --cache-dir ${{ env.CACHE_DIR }}
     - name: Scan container
       run: trivy image trivy --scanners vuln
