on:
 - push
 - workflow_dispatch

jobs:
   container_scanning_using_trivy:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v4.1.7
     - name: Build container image
       shell: pwsh
       run: ./build.ps1
     - name: Install Trivy
       shell: bash
       run: |
        sudo apt-get install wget apt-transport-https gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
     - name: Install Trivy
       run: trivy scan trivy --scanners vuln
